Public Class Countries
    Inherits List(Of Country)

    Public Sub New()
        Dim currencies As New Currencies()

        ' Afghanistan 
        Add(New Country(name:="Afghanistan",
                        officialName:="Islamic Republic of Afghanistan",
                        capitalCity:="Kabul",
                        countryCode:="AFG",
                        continent:="Asia",
                        affiliations:={"United Nations", "Collective Security Treaty Organization", "Organisation of Islamic Cooperation"},
                        areaInKM:=32225560,
                        highestPoint:=New CountryPoint("Noshaq", 7492),
                        lowestPoint:=New CountryPoint("Amu Darya", 0.258),
                        currency:=currencies("AFN"),
                        emoji:="🇦🇫",
                        flagImagePath:="af.png",
                        isIndependent:=True,
                        callingCode:=93,
                        topleveldomain:=".af"))

        ' Åland Islands 
        Add(New Country(name:="Åland Islands",
                        officialName:="Åland Islands",
                        capitalCity:="Mariehamn",
                        countryCode:="ALA",
                        continent:="Europe",
                        affiliations:={"Nordic Council"},
                        areaInKM:=1580,
                        highestPoint:=New CountryPoint("Orrdals Hill", 0.129),
                        lowestPoint:=New CountryPoint("Baltic Sea", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇦🇽",
                        flagImagePath:="ax.png",
                        isIndependent:=False,
                        callingCode:=35818,
                        topleveldomain:=".ax"))

        ' Albania
        Add(New Country(name:="Albania",
                        officialName:="Republic of Albania",
                        capitalCity:="Tirana",
                        countryCode:="ALB",
                        continent:="Europe",
                        affiliations:={"United Nations", "NATO", "Organisation of Islamic Cooperation"},
                        areaInKM:=28748,
                        highestPoint:=New CountryPoint("Korab ", 2.764),
                        lowestPoint:=New CountryPoint("Adriatic Sea", 0),
                        currency:=currencies("ALL"),
                        emoji:="🇦🇱",
                        flagImagePath:="al.png",
                        isIndependent:=True,
                        callingCode:=355,
                        topleveldomain:=".al"))

        ' Algeria
        Add(New Country(name:="Algeria",
                        officialName:="People's Democratic Republic of Algeria",
                        capitalCity:="Algiers",
                        countryCode:="DZA",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Arab League", "Organisation of Islamic Cooperation", "OPEC"},
                        areaInKM:=2381740,
                        highestPoint:=New CountryPoint("Mount Tahat", 3.003),
                        lowestPoint:=New CountryPoint("Chott Melrhir", -0.04),
                        currency:=currencies("DZD"),
                        emoji:="🇩🇿",
                        flagImagePath:="dz.png",
                        isIndependent:=True,
                        callingCode:=213,
                        topleveldomain:=".dz"))

        ' American Samoa
        Add(New Country(name:="American Samoa",
                        officialName:="American Samoa",
                        capitalCity:="Pago Pago",
                        countryCode:="ASM",
                        continent:="Oceania",
                        affiliations:={"Pacific Community"},
                        areaInKM:=199,
                        highestPoint:=New CountryPoint("Lata Mountain on Ta‘ū", 0.966),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("USD"),
                        emoji:="🇦🇸",
                        flagImagePath:="as.png",
                        isIndependent:=False,
                        callingCode:=1684,
                        topleveldomain:=".as"))

        ' Andorra
        Add(New Country(name:="Andorra",
                        officialName:="Principality of Andorra",
                        capitalCity:="Andorra la Vella",
                        countryCode:="AND",
                        continent:="Europe",
                        affiliations:={"United Nations"},
                        areaInKM:=468,
                        highestPoint:=New CountryPoint("Coma Pedrosa", 2.942),
                        lowestPoint:=New CountryPoint("Gran Valira", 0.84),
                        currency:=currencies("EUR"),
                        emoji:="🇦🇩",
                        flagImagePath:="ad.png",
                        isIndependent:=True,
                        callingCode:=213,
                        topleveldomain:=".ad"))


        ' Angola
        Add(New Country(name:="Angola",
                        officialName:="Republic of Angola",
                        capitalCity:="Luanda",
                        countryCode:="AGO",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Southern African Development Community", "OPEC"},
                        areaInKM:=1246700,
                        highestPoint:=New CountryPoint("Mount Moco", 2.62),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("AOA"),
                        emoji:="🇦🇴",
                        flagImagePath:="ao.png",
                        isIndependent:=True,
                        callingCode:=244,
                        topleveldomain:=".ao"))

        ' Anguilla 
        Add(New Country(name:="Anguilla",
                        officialName:="Anguilla",
                        capitalCity:="The Valley",
                        countryCode:="AIA",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=91,
                        highestPoint:=New CountryPoint("Crocus Hill", 0.65),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("XCD"),
                        emoji:="🇦🇮",
                        flagImagePath:="ai.png",
                        isIndependent:=False,
                        callingCode:=1264,
                        topleveldomain:=".ai"))

        ' Antigua and Barbuda 
        Add(New Country(name:="Antigua and Barbuda",
                        officialName:="Antigua and Barbuda",
                        capitalCity:="Saint John's",
                        countryCode:="ATG",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=442,
                        highestPoint:=New CountryPoint("Boggy Peak on Antigua", 0.402),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("XCD"),
                        emoji:="🇦🇬",
                        flagImagePath:="ag.png",
                        isIndependent:=True,
                        callingCode:=1268,
                        topleveldomain:=".ag"))

        ' Argentina 
        Add(New Country(name:="Argentina",
                        officialName:="Argentine Republic",
                        capitalCity:="Buenos Aires",
                        countryCode:="ARG",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=2780400,
                        highestPoint:=New CountryPoint("Aconcagua", 6.696),
                        lowestPoint:=New CountryPoint("Laguna del Carbón", -0.105),
                        currency:=currencies("ARS"),
                        emoji:="🇦🇷",
                        flagImagePath:="ar.png",
                        isIndependent:=True,
                        callingCode:=54,
                        topleveldomain:=".ar"))

        ' Argentina 
        Add(New Country(name:="Argentina",
                        officialName:="Argentine Republic",
                        capitalCity:="Buenos Aires",
                        countryCode:="ARG",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=2780400,
                        highestPoint:=New CountryPoint("Aconcagua", 6.696),
                        lowestPoint:=New CountryPoint("Laguna del Carbón", -0.105),
                        currency:=currencies("ARS"),
                        emoji:="🇦🇷",
                        flagImagePath:="ar.png",
                        isIndependent:=True,
                        callingCode:=54,
                        topleveldomain:=".ar"))

        ' Armenia 
        Add(New Country(name:="Armenia",
                        officialName:="Republic of Armenia",
                        capitalCity:="Yerevan",
                        countryCode:="ARM",
                        continent:="Asia",
                        affiliations:={"United Nations", "Collective Security Treaty Organization", "Commonwealth of Independent States", "Eurasian Economic Union"},
                        areaInKM:=29743,
                        highestPoint:=New CountryPoint("Mount Aragats", 4.09),
                        lowestPoint:=New CountryPoint("Debed", 0.4),
                        currency:=currencies("AMD"),
                        emoji:="🇦🇲",
                        flagImagePath:="am.png",
                        isIndependent:=True,
                        callingCode:=374,
                        topleveldomain:=".am"))

        ' Aruba  
        Add(New Country(name:="Aruba",
                        officialName:="Aruba",
                        capitalCity:="Oranjestad",
                        countryCode:="ABW",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=180,
                        highestPoint:=New CountryPoint("Mount Jamanota", 0.188),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("AWG"),
                        emoji:="🇦🇼",
                        flagImagePath:="aw.png",
                        isIndependent:=False,
                        callingCode:=297,
                        topleveldomain:=".aw"))

        ' Australia  
        Add(New Country(name:="Australia",
                        officialName:="Commonwealth of Australia",
                        capitalCity:="Canberra",
                        countryCode:="AUS",
                        continent:="Oceania",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Pacific Community"},
                        areaInKM:=7692020,
                        highestPoint:=New CountryPoint("Mount Kosciuszko", 2228),
                        lowestPoint:=New CountryPoint("Lake Eyre", -0.15),
                        currency:=currencies("AUD"),
                        emoji:="🇦🇺",
                        flagImagePath:="au.png",
                        isIndependent:=True,
                        callingCode:=61,
                        topleveldomain:=".au"))

        ' Austria  
        Add(New Country(name:="Austria",
                        officialName:="Republic of Austria",
                        capitalCity:="Vienna",
                        countryCode:="AUT",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union"},
                        areaInKM:=83871,
                        highestPoint:=New CountryPoint("Grossglockner", 3.798),
                        lowestPoint:=New CountryPoint("Lake Neusiedl", 0.115),
                        currency:=currencies("EUR"),
                        emoji:="🇦🇹",
                        flagImagePath:="at.png",
                        isIndependent:=True,
                        callingCode:=43,
                        topleveldomain:=".at"))

        ' Azerbaijan  
        Add(New Country(name:="Azerbaijan",
                        officialName:="Republic of Azerbaijan",
                        capitalCity:="Baku",
                        countryCode:="AZE",
                        continent:="Asia",
                        affiliations:={"United Nations", "Commonwealth of Independent States", "Turkic Council", "Organisation of Islamic Cooperation"},
                        areaInKM:=86600,
                        highestPoint:=New CountryPoint("Mount Bazardüzü", 4.485),
                        lowestPoint:=New CountryPoint("Caspian Sea", -0.28),
                        currency:=currencies("AZN"),
                        emoji:="🇦🇿",
                        flagImagePath:="az.png",
                        isIndependent:=True,
                        callingCode:=994,
                        topleveldomain:=".az"))

        ' Bahamas  
        Add(New Country(name:="Bahamas",
                        officialName:="Commonwealth of the Bahamas",
                        capitalCity:="Nassau",
                        countryCode:="BHS",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=13943,
                        highestPoint:=New CountryPoint("Mount Alvernia on Cat Island", 0.63),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("BSD"),
                        emoji:="🇧🇸",
                        flagImagePath:="bs.png",
                        isIndependent:=True,
                        callingCode:=1242,
                        topleveldomain:=".bs"))

        ' Bahrain  
        Add(New Country(name:="Bahrain",
                        officialName:="Kingdom of Bahrain",
                        capitalCity:="Manama",
                        countryCode:="BHR",
                        continent:="Asia",
                        affiliations:={"United Nations", "Gulf Cooperation Council", "Arab League", "Organisation of Islamic Cooperation"},
                        areaInKM:=778,
                        highestPoint:=New CountryPoint("Mountain of Smoke", 0.122),
                        lowestPoint:=New CountryPoint("Persian Gulf", 0),
                        currency:=currencies("BHD"),
                        emoji:="🇧🇭",
                        flagImagePath:="bh.png",
                        isIndependent:=True,
                        callingCode:=973,
                        topleveldomain:=".bh"))

        ' Bangladesh  
        Add(New Country(name:="Bangladesh",
                        officialName:="People's Republic of Bangladesh",
                        capitalCity:="Dhaka",
                        countryCode:="BDG",
                        continent:="Asia",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organisation of Islamic Cooperation"},
                        areaInKM:=147570,
                        highestPoint:=New CountryPoint("Saka Haphong", 1.052),
                        lowestPoint:=New CountryPoint("Bay of Bengal", 0),
                        currency:=currencies("BDT"),
                        emoji:="🇧🇩",
                        flagImagePath:="bd.png",
                        isIndependent:=True,
                        callingCode:=880,
                        topleveldomain:=".bd"))

        ' Barbados  
        Add(New Country(name:="Barbados",
                        officialName:="Barbados",
                        capitalCity:="Bridgetown",
                        countryCode:="BRB",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=430,
                        highestPoint:=New CountryPoint("Mount Hillaby", 0.336),
                        lowestPoint:=New CountryPoint("North Atlantic Ocean", 0),
                        currency:=currencies("BBD"),
                        emoji:="🇧🇧",
                        flagImagePath:="bb.png",
                        isIndependent:=True,
                        callingCode:=1246,
                        topleveldomain:=".bb"))

        ' Belarus  
        Add(New Country(name:="Belarus",
                        officialName:="Republic of Belarus",
                        capitalCity:="Minsk",
                        countryCode:="BLR",
                        continent:="Europe",
                        affiliations:={"United Nations", "Collective Security Treaty Organization", "Commonwealth of Independent States", "Eurasian Economic Union"},
                        areaInKM:=207600,
                        highestPoint:=New CountryPoint("Dzyarzhynskaya Hara", 0.346),
                        lowestPoint:=New CountryPoint("Neman", 0.09),
                        currency:=currencies("BYR"),
                        emoji:="🇧🇾",
                        flagImagePath:="by.png",
                        isIndependent:=True,
                        callingCode:=375,
                        topleveldomain:=".by"))

        ' Belgium  
        Add(New Country(name:="Belgium",
                        officialName:="Kingdom of Belgium",
                        capitalCity:="Brussels",
                        countryCode:="BEL",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=30528,
                        highestPoint:=New CountryPoint("Signal de Botrange", 0.694),
                        lowestPoint:=New CountryPoint("De Moeren", -0.003),
                        currency:=currencies("EUR"),
                        emoji:="🇧🇪",
                        flagImagePath:="be.png",
                        isIndependent:=True,
                        callingCode:=32,
                        topleveldomain:=".be"))

        ' Belize  
        Add(New Country(name:="Belize",
                        officialName:="Belize",
                        capitalCity:="Belmopan",
                        countryCode:="BLZ",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community", "Central American Integration System"},
                        areaInKM:=22.966,
                        highestPoint:=New CountryPoint("Doyle's Delight", 1.124),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("BZD"),
                        emoji:="🇧🇿",
                        flagImagePath:="bz.png",
                        isIndependent:=True,
                        callingCode:=501,
                        topleveldomain:=".bz"))


        ' Benin  
        Add(New Country(name:="Benin",
                        officialName:="Republic of Benin",
                        capitalCity:="Porto-Novo",
                        countryCode:="BEN",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=114763,
                        highestPoint:=New CountryPoint("Mont Sokbaro", 0.658),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("XOF"),
                        emoji:="🇧🇯",
                        flagImagePath:="bj.png",
                        isIndependent:=True,
                        callingCode:=229,
                        topleveldomain:=".bj"))


        ' Bermuda  
        Add(New Country(name:="Bermuda",
                        officialName:="Bermuda",
                        capitalCity:="Hamilton",
                        countryCode:="BMU",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=54,
                        highestPoint:=New CountryPoint("Town Hill", 0.076),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("BMD"),
                        emoji:="🇧🇲",
                        flagImagePath:="bm.png",
                        isIndependent:=False,
                        callingCode:=1441,
                        topleveldomain:=".bm"))

        ' Bhutan  
        Add(New Country(name:="Bhutan",
                        officialName:="Kingdom of Bhutan",
                        capitalCity:="Thimphu",
                        countryCode:="BTN",
                        continent:="Asia",
                        affiliations:={"United Nations"},
                        areaInKM:=38394,
                        highestPoint:=New CountryPoint("Gangkhar Puensum", 7.57),
                        lowestPoint:=New CountryPoint("Drangme Chhu", 0.097),
                        currency:=currencies("BTN"),
                        emoji:="🇧🇹",
                        flagImagePath:="bt.png",
                        isIndependent:=True,
                        callingCode:=975,
                        topleveldomain:=".bt"))

        ' Bolivia  
        Add(New Country(name:="Bolivia",
                        officialName:="Plurinational State of Bolivia",
                        capitalCity:="Sucre",
                        countryCode:="BOL",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=1098580,
                        highestPoint:=New CountryPoint("Sajama", 6.542),
                        lowestPoint:=New CountryPoint("Paraguay River", 0.09),
                        currency:=currencies("BOB"),
                        emoji:="🇧🇴",
                        flagImagePath:="bo.png",
                        isIndependent:=True,
                        callingCode:=591,
                        topleveldomain:=".bo"))

        ' Bosnia and Herzegovina  
        Add(New Country(name:="Bosnia and Herzegovina",
                        officialName:="Bosnia and Herzegovina",
                        capitalCity:="Sarajevo",
                        countryCode:="BIH",
                        continent:="Europe",
                        affiliations:={"United Nations"},
                        areaInKM:=51209,
                        highestPoint:=New CountryPoint("Maglić", 2.3686),
                        lowestPoint:=New CountryPoint("Adriatic Sea", 0),
                        currency:=currencies("BAM"),
                        emoji:="🇧🇦",
                        flagImagePath:="ba.png",
                        isIndependent:=True,
                        callingCode:=387,
                        topleveldomain:=".ba"))

        ' Botswana  
        Add(New Country(name:="Botswana",
                        officialName:="Republic of Botswana",
                        capitalCity:="Gaborone",
                        countryCode:="BWA",
                        continent:="Africa",
                        affiliations:={"United Nations", "Commonwealth of Nations", "African Union", "Southern African Development Community"},
                        areaInKM:=581730,
                        highestPoint:=New CountryPoint("Otse Hill", 1.491),
                        lowestPoint:=New CountryPoint("Confluence of Limpopo River and Shashe River", 0.513),
                        currency:=currencies("BWP"),
                        emoji:="🇧🇼",
                        flagImagePath:="bw.png",
                        isIndependent:=True,
                        callingCode:=267,
                        topleveldomain:=".bw"))

        ' Bouvet Island  
        Add(New Country(name:="Bouvet Island",
                        officialName:="Bouvet Island",
                        capitalCity:=Nothing,
                        countryCode:="BVT",
                        continent:=Nothing,
                        affiliations:=Nothing,
                        areaInKM:=49,
                        highestPoint:=New CountryPoint("Olavtoppen", 0.935),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("BWP"),
                        emoji:="🇧🇼",
                        flagImagePath:="bw.png",
                        isIndependent:=False,
                        callingCode:=267,
                        topleveldomain:=".bw"))

        ' Brazil  
        Add(New Country(name:="Brazil",
                        officialName:="Federative Republic of Brazil",
                        capitalCity:="Brasília",
                        countryCode:="BRA",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=8515770,
                        highestPoint:=New CountryPoint("Pico da Neblina", 2.995),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("BRL"),
                        emoji:="🇧🇷",
                        flagImagePath:="br.png",
                        isIndependent:=True,
                        callingCode:=55,
                        topleveldomain:=".br"))

        ' British Indian Ocean Territory  
        Add(New Country(name:="British Indian Ocean Territory",
                        officialName:="British Indian Ocean Territory",
                        capitalCity:="Diego Garcia",
                        countryCode:="IOT",
                        continent:="Africa",
                        affiliations:=Nothing,
                        areaInKM:=60,
                        highestPoint:=New CountryPoint("Diego Garcia", 0.015),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("USD"),
                        emoji:="🇮🇴",
                        flagImagePath:="io.png",
                        isIndependent:=False,
                        callingCode:=246,
                        topleveldomain:=".io"))

        ' Brunei
        Add(New Country(name:="Brunei",
                        officialName:="Nation of Brunei, Abode of Peace",
                        capitalCity:="Bandar Seri Begawan",
                        countryCode:="BRN",
                        continent:="Asia",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Association of Southeast Asian Nations", "Organisation of Islamic Cooperation"},
                        areaInKM:=5765,
                        highestPoint:=New CountryPoint("Bukit Pagon", 1.85),
                        lowestPoint:=New CountryPoint("China Sea", 0),
                        currency:=currencies("BND"),
                        emoji:="🇧🇳",
                        flagImagePath:="bn.png",
                        isIndependent:=True,
                        callingCode:=673,
                        topleveldomain:=".bn"))

        ' Bulgaria
        Add(New Country(name:="Bulgaria",
                        officialName:="Republic of Bulgaria",
                        capitalCity:="Sofia",
                        countryCode:="BGR",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=111002,
                        highestPoint:=New CountryPoint("Musala", 2.925),
                        lowestPoint:=New CountryPoint("Black Sea", 0),
                        currency:=currencies("BGN"),
                        emoji:="🇧🇳",
                        flagImagePath:="bg.png",
                        isIndependent:=True,
                        callingCode:=359,
                        topleveldomain:=".bg"))

        ' Burkina Faso
        Add(New Country(name:="Burkina Faso",
                        officialName:="Burkina Faso",
                        capitalCity:="Ouagadougou",
                        countryCode:="BFA",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=274222,
                        highestPoint:=New CountryPoint("Mount Tenakourou", 0.749),
                        lowestPoint:=New CountryPoint("Black Volta", 0.2),
                        currency:=currencies("XOF"),
                        emoji:="🇧🇫",
                        flagImagePath:="bf.png",
                        isIndependent:=True,
                        callingCode:=226,
                        topleveldomain:=".bf"))

        ' Burundi
        Add(New Country(name:="Burundi",
                        officialName:="Republic of Burundi",
                        capitalCity:="Bujumbura",
                        countryCode:="BDI",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "East African Community"},
                        areaInKM:=27834,
                        highestPoint:=New CountryPoint("Mount Heha", 2.684),
                        lowestPoint:=New CountryPoint("Lake Tanganyika", 0.772),
                        currency:=currencies("BIF"),
                        emoji:="🇧🇮",
                        flagImagePath:="bi.png",
                        isIndependent:=True,
                        callingCode:=257,
                        topleveldomain:=".bi"))

        ' Cambodia
        Add(New Country(name:="Cambodia",
                        officialName:="Kingdom of Cambodia",
                        capitalCity:="Phnom Penh",
                        countryCode:="KHM",
                        continent:="Asia",
                        affiliations:={"United Nations", "Association of Southeast Asian Nations"},
                        areaInKM:=181035,
                        highestPoint:=New CountryPoint("Phnom Aural", 1.18),
                        lowestPoint:=New CountryPoint("Gulf of Thailand", 0),
                        currency:=currencies("KHR"),
                        emoji:="🇰🇭",
                        flagImagePath:="kh.png",
                        isIndependent:=True,
                        callingCode:=855,
                        topleveldomain:=".kh"))

        ' Cameroon
        Add(New Country(name:="Cameroon",
                        officialName:="Republic of Cameroon",
                        capitalCity:="Yaoundé",
                        countryCode:="CMR",
                        continent:="Africa",
                        affiliations:={"United Nations", "Commonwealth of Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=475442,
                        highestPoint:=New CountryPoint("Mount Cameroon", 4.04),
                        lowestPoint:=New CountryPoint("Bight of Bonny", 0),
                        currency:=currencies("XAF"),
                        emoji:="🇨🇲",
                        flagImagePath:="cm.png",
                        isIndependent:=True,
                        callingCode:=237,
                        topleveldomain:=".cm"))

        ' Canada
        Add(New Country(name:="Canada",
                        officialName:="Canada",
                        capitalCity:="Ottawa",
                        countryCode:="CAN",
                        continent:="North America",
                        affiliations:={"United Nations", "NATO", "Commonwealth of Nations", "Organization of American States"},
                        areaInKM:=9984670,
                        highestPoint:=New CountryPoint("Mount Logan", 5.959),
                        lowestPoint:=New CountryPoint("Atlantic Ocean, Arctic Ocean, Pacific Ocean", 0),
                        currency:=currencies("CAD"),
                        emoji:="🇨🇦",
                        flagImagePath:="ca.png",
                        isIndependent:=True,
                        callingCode:=1,
                        topleveldomain:=".ca"))

        ' Cape Verde
        Add(New Country(name:="Cape Verde",
                        officialName:="Republic of Cabo Verde",
                        capitalCity:="Praia",
                        countryCode:="CPV",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union"},
                        areaInKM:=4033,
                        highestPoint:=New CountryPoint("Pico do Fogo", 2.829),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("CVE"),
                        emoji:="🇨🇻",
                        flagImagePath:="cv.png",
                        isIndependent:=True,
                        callingCode:=238,
                        topleveldomain:=".cv"))

        ' Caribbean Netherlands
        Add(New Country(name:="Caribbean Netherlands",
                        officialName:="Bonaire, Sint Eustatius and Saba",
                        capitalCity:=Nothing,
                        countryCode:="BES",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=328,
                        highestPoint:=New CountryPoint("Mount Scenery", 0.887),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("USD"),
                        emoji:="🇧🇶",
                        flagImagePath:="ba.png",
                        isIndependent:=False,
                        callingCode:=599,
                        topleveldomain:=".bq"))

        ' Cayman Islands
        Add(New Country(name:="Cayman Islands",
                        officialName:="Cayman Islands",
                        capitalCity:="George Town",
                        countryCode:="CYM",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=264,
                        highestPoint:=New CountryPoint("The Bluff on Cayman Brac", 0.46),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("KYD"),
                        emoji:="🇰🇾",
                        flagImagePath:="ky.png",
                        isIndependent:=False,
                        callingCode:=1345,
                        topleveldomain:=".ky"))

        ' Central African Republic
        Add(New Country(name:="Central African Republic",
                        officialName:="Central African Republic",
                        capitalCity:="Bangui",
                        countryCode:="CAF",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union"},
                        areaInKM:=622984,
                        highestPoint:=New CountryPoint("Mont Ngaoui ", 1.42),
                        lowestPoint:=New CountryPoint("Ubangi River", 0.335),
                        currency:=currencies("XAF"),
                        emoji:="🇨🇫",
                        flagImagePath:="cf.png",
                        isIndependent:=True,
                        callingCode:=236,
                        topleveldomain:=".cf"))

        ' Chad
        Add(New Country(name:="Chad",
                        officialName:="Republic of Chad",
                        capitalCity:="N'Djamena",
                        countryCode:="TCD",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=1284000,
                        highestPoint:=New CountryPoint("Emi Koussi", 3.445),
                        lowestPoint:=New CountryPoint("Djourab Depression", 0.16),
                        currency:=currencies("XAF"),
                        emoji:="🇹🇩",
                        flagImagePath:="td.png",
                        isIndependent:=True,
                        callingCode:=235,
                        topleveldomain:=".td"))

        ' Chile
        Add(New Country(name:="Chile",
                        officialName:="Republic of Chile",
                        capitalCity:="Santiago",
                        countryCode:="TCD",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=756102,
                        highestPoint:=New CountryPoint("Ojos del Salado", 6.893),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("CLP"),
                        emoji:="🇨🇱",
                        flagImagePath:="cl.png",
                        isIndependent:=True,
                        callingCode:=56,
                        topleveldomain:=".cl"))

        ' China
        Add(New Country(name:="China",
                        officialName:="People's Republic of China",
                        capitalCity:="Beijing",
                        countryCode:="CHN",
                        continent:="Asia",
                        affiliations:={"United Nations"},
                        areaInKM:=9596960,
                        highestPoint:=New CountryPoint("Mount Everest", 8.848),
                        lowestPoint:=New CountryPoint("Ayding Lake", -0.154),
                        currency:=currencies("CNY"),
                        emoji:="🇨🇳",
                        flagImagePath:="cn.png",
                        isIndependent:=True,
                        callingCode:=86,
                        topleveldomain:=".cn"))

        ' Christmas Island
        Add(New Country(name:="Christmas Island",
                        officialName:="Territory of Christmas Island",
                        capitalCity:="Flying Fish Cove",
                        countryCode:="CXR",
                        continent:="Oceania",
                        affiliations:=Nothing,
                        areaInKM:=135,
                        highestPoint:=New CountryPoint("Murray Hill", 361),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("AUD"),
                        emoji:="🇨🇽",
                        flagImagePath:="cx.png",
                        isIndependent:=False,
                        callingCode:=61,
                        topleveldomain:=".cx"))

        ' Cocos Islands
        Add(New Country(name:="Cocos Islands",
                        officialName:="Territory of the Cocos Islands",
                        capitalCity:="West Island",
                        countryCode:="CCK",
                        continent:="Oceania",
                        affiliations:=Nothing,
                        areaInKM:=14,
                        highestPoint:=New CountryPoint("West Island", 0.005),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("AUD"),
                        emoji:="🇨🇨",
                        flagImagePath:="cc.png",
                        isIndependent:=False,
                        callingCode:=61,
                        topleveldomain:=".cc"))

        ' Colombia 
        Add(New Country(name:="Colombia",
                        officialName:="Republic of Colombia",
                        capitalCity:="Bogotá",
                        countryCode:="COL",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=1141750,
                        highestPoint:=New CountryPoint("Pico Cristóbal Colón", 5.7),
                        lowestPoint:=New CountryPoint("Pacific Ocean, Caribbean Sea", 0),
                        currency:=currencies("COP"),
                        emoji:="🇨🇴",
                        flagImagePath:="co.png",
                        isIndependent:=True,
                        callingCode:=57,
                        topleveldomain:=".co"))

        ' Comoros 
        Add(New Country(name:="Comoros",
                        officialName:="Union of the Comoros",
                        capitalCity:="Moroni",
                        countryCode:="COM",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Southern African Development Community", "Arab League", "Organisation of Islamic Cooperation"},
                        areaInKM:=1862,
                        highestPoint:=New CountryPoint("Mount Karthala", 2.36),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("KMF"),
                        emoji:="🇰🇲",
                        flagImagePath:="km.png",
                        isIndependent:=True,
                        callingCode:=269,
                        topleveldomain:=".km"))

        ' Congo
        Add(New Country(name:="Congo",
                        officialName:="Republic of the Congo",
                        capitalCity:="Brazzaville",
                        countryCode:="COG",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "OPEC"},
                        areaInKM:=342000,
                        highestPoint:=New CountryPoint("Mont Nabemba", 1.02),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("XAF"),
                        emoji:="🇨🇬",
                        flagImagePath:="cg.png",
                        isIndependent:=True,
                        callingCode:=242,
                        topleveldomain:=".cg"))

        ' Democratic Republic of the Congo
        Add(New Country(name:="Congo",
                        officialName:="Democratic Republic of the Congo",
                        capitalCity:="Kinshasa",
                        countryCode:="COD",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Southern African Development Community"},
                        areaInKM:=2344860,
                        highestPoint:=New CountryPoint("Mount Stanley", 5.109),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("CDF"),
                        emoji:="🇨🇩",
                        flagImagePath:="cd.png",
                        isIndependent:=True,
                        callingCode:=243,
                        topleveldomain:=".cd"))

        ' Cook Islands
        Add(New Country(name:="Cook Islands",
                        officialName:="Cook Islands",
                        capitalCity:="Avarua",
                        countryCode:="COK",
                        continent:="Oceania",
                        affiliations:={"Pacific Community"},
                        areaInKM:=236,
                        highestPoint:=New CountryPoint("Te Manga on Rarotonga", 0.652),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("NZD"),
                        emoji:="🇨🇰",
                        flagImagePath:="ck.png",
                        isIndependent:=True,
                        callingCode:=682,
                        topleveldomain:=".ck"))

        ' Cook Islands
        Add(New Country(name:="Cook Islands",
                        officialName:="Cook Islands",
                        capitalCity:="Avarua",
                        countryCode:="COK",
                        continent:="Oceania",
                        affiliations:={"Pacific Community"},
                        areaInKM:=236,
                        highestPoint:=New CountryPoint("Te Manga on Rarotonga", 0.652),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("NZD"),
                        emoji:="🇨🇰",
                        flagImagePath:="ck.png",
                        isIndependent:=False,
                        callingCode:=682,
                        topleveldomain:=".ck"))

        ' Costa Rica
        Add(New Country(name:="Costa Rica",
                        officialName:="Republic of Costa Rica",
                        capitalCity:="San José",
                        countryCode:="CRI",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Central American Integration System"},
                        areaInKM:=51100,
                        highestPoint:=New CountryPoint("Cerro Chirripó", 3.82),
                        lowestPoint:=New CountryPoint("Pacific Ocean, Caribbean Sea", 0),
                        currency:=currencies("CRC"),
                        emoji:="🇨🇷",
                        flagImagePath:="cr.png",
                        isIndependent:=True,
                        callingCode:=506,
                        topleveldomain:=".cr"))

        ' Côte d'Ivoire
        Add(New Country(name:="Ivory Coast",
                        officialName:="Republic of Côte d'Ivoire",
                        capitalCity:="Yamoussoukro",
                        countryCode:="CIV",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=322463,
                        highestPoint:=New CountryPoint("Mont Nimba", 1.752),
                        lowestPoint:=New CountryPoint("Gulf of Guinea", 0),
                        currency:=currencies("XOF"),
                        emoji:="🇨🇮",
                        flagImagePath:="ci.png",
                        isIndependent:=True,
                        callingCode:=225,
                        topleveldomain:=".ci"))

        ' Croatia
        Add(New Country(name:="Croatia",
                        officialName:="Republic of Croatia",
                        capitalCity:="Zagreb",
                        countryCode:="HRV",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=56594,
                        highestPoint:=New CountryPoint("Dinara", 1.831),
                        lowestPoint:=New CountryPoint("Adriatic Sea", 0),
                        currency:=currencies("HRK"),
                        emoji:="🇭🇷",
                        flagImagePath:="hr.png",
                        isIndependent:=True,
                        callingCode:=385,
                        topleveldomain:=".hr"))

        ' Cuba
        Add(New Country(name:="Cuba",
                        officialName:="Republic of Cuba",
                        capitalCity:="Havana",
                        countryCode:="CUB",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States"},
                        areaInKM:=109884,
                        highestPoint:=New CountryPoint("Pico Turquino", 1.974),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("CUC"),
                        emoji:="🇨🇺",
                        flagImagePath:="cu.png",
                        isIndependent:=True,
                        callingCode:=53,
                        topleveldomain:=".cu"))

        ' Curaçao
        Add(New Country(name:="Curaçao",
                        officialName:="Country of Curaçao",
                        capitalCity:="Willemstad",
                        countryCode:="CUW",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=444,
                        highestPoint:=New CountryPoint("Christoffelberg", 0.375),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("ANG"),
                        emoji:="🇨🇼",
                        flagImagePath:="cw.png",
                        isIndependent:=False,
                        callingCode:=599,
                        topleveldomain:=".cw"))

        ' Cyprus
        Add(New Country(name:="Cyprus",
                        officialName:="Republic of Cyprus",
                        capitalCity:="Nicosia",
                        countryCode:="CYP",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "Commonwealth of Nations"},
                        areaInKM:=9251,
                        highestPoint:=New CountryPoint("Mount Olympus", 1.951),
                        lowestPoint:=New CountryPoint("Mediterranean Sea", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇨🇾",
                        flagImagePath:="cy.png",
                        isIndependent:=True,
                        callingCode:=357,
                        topleveldomain:=".cy"))

        ' Czechia
        Add(New Country(name:="Czechia",
                        officialName:="Czech Republic",
                        capitalCity:="Prague",
                        countryCode:="CZE",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=78865,
                        highestPoint:=New CountryPoint("Sněžka", 1.603),
                        lowestPoint:=New CountryPoint("Elbe", 0.115),
                        currency:=currencies("CZK"),
                        emoji:="🇨🇿",
                        flagImagePath:="cz.png",
                        isIndependent:=True,
                        callingCode:=420,
                        topleveldomain:=".cz"))

        ' Denmark
        Add(New Country(name:="Denmark",
                        officialName:="Kingdom of Denmark",
                        capitalCity:="Copenhagen",
                        countryCode:="DNK",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO", "Nordic Council"},
                        areaInKM:=43094,
                        highestPoint:=New CountryPoint("Møllehøj", 0.171),
                        lowestPoint:=New CountryPoint("Lammefjord", -0.007),
                        currency:=currencies("DKK"),
                        emoji:="🇩🇰",
                        flagImagePath:="dk.png",
                        isIndependent:=True,
                        callingCode:=45,
                        topleveldomain:=".dk"))

        ' Djibouti
        Add(New Country(name:="Djibouti",
                        officialName:="Republic of Djibouti",
                        capitalCity:="Djibouti",
                        countryCode:="DJI",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Arab League", "Organisation of Islamic Cooperation"},
                        areaInKM:=23200,
                        highestPoint:=New CountryPoint("Mousa Ali", 2.028),
                        lowestPoint:=New CountryPoint("Lake Assal", -0.155),
                        currency:=currencies("DKK"),
                        emoji:="🇩🇯",
                        flagImagePath:="dj.png",
                        isIndependent:=True,
                        callingCode:=253,
                        topleveldomain:=".dj"))

        ' Dominica
        Add(New Country(name:="Dominica",
                        officialName:="Commonwealth of Dominica",
                        capitalCity:="Roseau",
                        countryCode:="DMA",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=751,
                        highestPoint:=New CountryPoint("Morne Diablotins", 1.447),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("XCD"),
                        emoji:="🇩🇲",
                        flagImagePath:="dm.png",
                        isIndependent:=True,
                        callingCode:=1767,
                        topleveldomain:=".dm"))

        ' Dominican Republic | Other calling codes 1829, 1849
        Add(New Country(name:="Dominican Republic",
                        officialName:="Dominican Republic",
                        capitalCity:="Santo Domingo",
                        countryCode:="DOM",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Central American Integration System"},
                        areaInKM:=48671,
                        highestPoint:=New CountryPoint("Pico Duarte", 3.098),
                        lowestPoint:=New CountryPoint("Lago Enriquillo", 0.045),
                        currency:=currencies("DOP"),
                        emoji:="🇩🇴",
                        flagImagePath:="do.png",
                        isIndependent:=True,
                        callingCode:=1809,
                        topleveldomain:=".do"))

        ' Ecuador
        Add(New Country(name:="Ecuador",
                        officialName:="Republic of Ecuador",
                        capitalCity:="Quito",
                        countryCode:="ECU",
                        continent:="South America",
                        affiliations:={"United Nations", "Organization of American States", "Union of South American Nations"},
                        areaInKM:=276841,
                        highestPoint:=New CountryPoint("Chimborazo", 6.627),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("USD"),
                        emoji:="🇪🇨",
                        flagImagePath:="ec.png",
                        isIndependent:=True,
                        callingCode:=589,
                        topleveldomain:=".ec"))

        ' Egypt | continent: Africa; Asia | topleveldomain: .eg, .مصر
        Add(New Country(name:="Egypt",
                        officialName:="Arab Republic of Egypt",
                        capitalCity:="Cairo",
                        countryCode:="EGY",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Arab League", "Organisation of Islamic Cooperation"},
                        areaInKM:=1002450,
                        highestPoint:=New CountryPoint("Mount Catherine", 2.629),
                        lowestPoint:=New CountryPoint("Qattara Depression", -0.133),
                        currency:=currencies("EGP"),
                        emoji:="🇪🇬",
                        flagImagePath:="eg.png",
                        isIndependent:=True,
                        callingCode:=20,
                        topleveldomain:=".eg"))

        ' El Salvador
        Add(New Country(name:="El Salvador",
                        officialName:="Republic of El Salvador",
                        capitalCity:="San Salvador",
                        countryCode:="SLV",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Central American Integration System"},
                        areaInKM:=21041,
                        highestPoint:=New CountryPoint("Cerro El Pital", 2.73),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("USD"),
                        emoji:="🇸🇻",
                        flagImagePath:="sv.png",
                        isIndependent:=True,
                        callingCode:=503,
                        topleveldomain:=".sv"))


        ' England
        Add(New Country(name:="England",
                        officialName:="England",
                        capitalCity:="London",
                        countryCode:="GB-ENG",
                        continent:="Europe",
                        affiliations:=Nothing,
                        areaInKM:=130279,
                        highestPoint:=New CountryPoint("Scafell Pike", 0.978),
                        lowestPoint:=New CountryPoint("Holme Fen", -0.0275),
                        currency:=currencies("GBP"),
                        emoji:="🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                        flagImagePath:="gb-eng.png",
                        isIndependent:=False,
                        callingCode:=44,
                        topleveldomain:=".uk"))

        ' Equatorial Guinea
        Add(New Country(name:="Equatorial Guinea",
                        officialName:="Republic of Equatorial Guinea",
                        capitalCity:="Malabo",
                        countryCode:="GNQ",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union"},
                        areaInKM:=28051,
                        highestPoint:=New CountryPoint("Pico Basile on Bioko", 3.008),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("XAF"),
                        emoji:="🇬🇶",
                        flagImagePath:="gq.png",
                        isIndependent:=True,
                        callingCode:=240,
                        topleveldomain:=".gq"))

        ' Eritrea
        Add(New Country(name:="Eritrea",
                        officialName:="State of Eritrea",
                        capitalCity:="Asmara",
                        countryCode:="ERI",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union"},
                        areaInKM:=117600,
                        highestPoint:=New CountryPoint("Emba Soira", 3.018),
                        lowestPoint:=New CountryPoint("Lake Kulul", 0.075),
                        currency:=currencies("ERN"),
                        emoji:="🇪🇷",
                        flagImagePath:="er.png",
                        isIndependent:=True,
                        callingCode:=291,
                        topleveldomain:=".er"))

        ' Estonia
        Add(New Country(name:="Estonia",
                        officialName:="Republic of Estonia",
                        capitalCity:="Tallinn",
                        countryCode:="EST",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=45227,
                        highestPoint:=New CountryPoint("Suur Munamägi", 0.318),
                        lowestPoint:=New CountryPoint("Baltic Sea", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇪🇪",
                        flagImagePath:="ee.png",
                        isIndependent:=True,
                        callingCode:=372,
                        topleveldomain:=".ee"))

        ' Eswatini
        Add(New Country(name:="Eswatini",
                        officialName:="Kingdom of Eswatini",
                        capitalCity:="Lobamba",
                        countryCode:="SWZ",
                        continent:="Africa",
                        affiliations:={"United Nations", "Commonwealth of Nations", "African Union", "Southern African Development Community"},
                        areaInKM:=17364,
                        highestPoint:=New CountryPoint("Emlembe", 1.862),
                        lowestPoint:=New CountryPoint("Maputo River", 0.021),
                        currency:=currencies("SZL"),
                        emoji:="🇸🇿",
                        flagImagePath:="sz.png",
                        isIndependent:=True,
                        callingCode:=268,
                        topleveldomain:=".sz"))

        ' Ethiopia
        Add(New Country(name:="Ethiopia",
                        officialName:="Federal Democratic Republic of Ethiopia",
                        capitalCity:="Addis Ababa",
                        countryCode:="ETH",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union"},
                        areaInKM:=1104300,
                        highestPoint:=New CountryPoint("Ras Dejen", 4.55),
                        lowestPoint:=New CountryPoint("Danakil Depression", -0.125),
                        currency:=currencies("EBT"),
                        emoji:="🇪🇹",
                        flagImagePath:="et.png",
                        isIndependent:=True,
                        callingCode:=251,
                        topleveldomain:=".et"))

        ' Falkland Islands
        Add(New Country(name:="Falkland Islands",
                        officialName:="Falkland Islands",
                        capitalCity:="Stanley",
                        countryCode:="FLK",
                        continent:="South America",
                        affiliations:=Nothing,
                        areaInKM:=12173,
                        highestPoint:=New CountryPoint("Mount Usborne", 0.705),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("FKP"),
                        emoji:="🇫🇰",
                        flagImagePath:="fk.png",
                        isIndependent:=False,
                        callingCode:=500,
                        topleveldomain:=".fk"))

        ' Faroe Islands
        Add(New Country(name:="Faroe Islands",
                        officialName:="Faroe Islands",
                        capitalCity:="Tórshavn",
                        countryCode:="FRO",
                        continent:="Europe",
                        affiliations:={"Nordic Council"},
                        areaInKM:=1393,
                        highestPoint:=New CountryPoint("Slættaratindur", 0.88),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("FOK"),
                        emoji:="🇫🇴",
                        flagImagePath:="fo.png",
                        isIndependent:=False,
                        callingCode:=298,
                        topleveldomain:=".fo"))

        ' Fiji
        Add(New Country(name:="Fiji",
                        officialName:="Republic of Fiji",
                        capitalCity:="Suva",
                        countryCode:="FJI",
                        continent:="Oceania",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Pacific Community"},
                        areaInKM:=18272,
                        highestPoint:=New CountryPoint("Tomanivi on Viti Levu", 1.324),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("FJD"),
                        emoji:="🇫🇯",
                        flagImagePath:="fj.png",
                        isIndependent:=True,
                        callingCode:=679,
                        topleveldomain:=".fj"))

        ' Finland
        Add(New Country(name:="Finland",
                        officialName:="Republic of Finland",
                        capitalCity:="Helsinki",
                        countryCode:="FIN",
                        continent:="Europe",
                        affiliations:={"United Nations, European Union, Nordic Council"},
                        areaInKM:=338424,
                        highestPoint:=New CountryPoint("Halti", 1.324),
                        lowestPoint:=New CountryPoint("Baltic Sea", 0),
                        currency:=currencies("FIN"),
                        emoji:="🇫🇮",
                        flagImagePath:="fi.png",
                        isIndependent:=True,
                        callingCode:=358,
                        topleveldomain:=".fi"))

        ' France
        Add(New Country(name:="France",
                        officialName:="French Republic",
                        capitalCity:="Paris",
                        countryCode:="FRA",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO", "Pacific Community"},
                        areaInKM:=640679,
                        highestPoint:=New CountryPoint("Mont Blanc", 4.81),
                        lowestPoint:=New CountryPoint("Étang de Lavalduc", -0.01),
                        currency:=currencies("EUR"),
                        emoji:="🇫🇷",
                        flagImagePath:="fr.png",
                        isIndependent:=True,
                        callingCode:=33,
                        topleveldomain:=".fr"))

        ' French Guiana
        Add(New Country(name:="French Guiana",
                        officialName:="Guiana",
                        capitalCity:="Cayenne",
                        countryCode:="GUF",
                        continent:="South America",
                        affiliations:=Nothing,
                        areaInKM:=83534,
                        highestPoint:=New CountryPoint("Bellevue de l'Inini", 0.851),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇬🇫",
                        flagImagePath:="gf.png",
                        isIndependent:=False,
                        callingCode:=594,
                        topleveldomain:=".gf"))

        ' French Polynesia
        Add(New Country(name:="French Polynesia",
                        officialName:="French Polynesia",
                        capitalCity:="Papeetē",
                        countryCode:="PYF",
                        continent:="Oceania",
                        affiliations:=Nothing,
                        areaInKM:=4167,
                        highestPoint:=New CountryPoint("Mont Orohena", 0.851),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("XPF"),
                        emoji:="🇵🇫",
                        flagImagePath:="pf.png",
                        isIndependent:=False,
                        callingCode:=689,
                        topleveldomain:=".pf"))

        ' French Southern and Antarctic Lands
        Add(New Country(name:="French Southern and Antarctic Lands",
                        officialName:="Territory of the French Southern and Antarctic Lands",
                        capitalCity:="Port-aux-Français",
                        countryCode:="ATF",
                        continent:=Nothing,
                        affiliations:=Nothing,
                        areaInKM:=7747,
                        highestPoint:=New CountryPoint("Mont Ross", 1.85),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇹🇫",
                        flagImagePath:="tf.png",
                        isIndependent:=False,
                        callingCode:=262,
                        topleveldomain:=".tf"))

        ' Gabon
        Add(New Country(name:="Gabon",
                        officialName:="Gabonese Republic",
                        capitalCity:="Libreville",
                        countryCode:="GAB",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation", "OPEC"},
                        areaInKM:=267668,
                        highestPoint:=New CountryPoint("Mont Bengoué", 1.07),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("XAF"),
                        emoji:="🇬🇦",
                        flagImagePath:="ga.png",
                        isIndependent:=True,
                        callingCode:=241,
                        topleveldomain:=".ga"))

        ' Gambia
        Add(New Country(name:="Gambia",
                        officialName:="Republic of the Gambia",
                        capitalCity:="Banjul",
                        countryCode:="GMB",
                        continent:="Africa",
                        affiliations:={"United Nations", "Commonwealth of Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=11295,
                        highestPoint:=New CountryPoint("Banjul", 0.064),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("GMD"),
                        emoji:="🇬🇲",
                        flagImagePath:="gm.png",
                        isIndependent:=True,
                        callingCode:=220,
                        topleveldomain:=".gm"))

        ' Georgia
        Add(New Country(name:="Georgia",
                        officialName:="Georgia",
                        capitalCity:="Tbilisi",
                        countryCode:="GEO",
                        continent:="Asia",
                        affiliations:={"United Nations"},
                        areaInKM:=69700,
                        highestPoint:=New CountryPoint("Shkhara", 5.201),
                        lowestPoint:=New CountryPoint("Black Sea", 0),
                        currency:=currencies("GEL"),
                        emoji:="🇬🇪",
                        flagImagePath:="ge.png",
                        isIndependent:=True,
                        callingCode:=995,
                        topleveldomain:=".ge"))

        ' Germany
        Add(New Country(name:="Germany",
                        officialName:="Federal Republic of Germany",
                        capitalCity:="Berlin",
                        countryCode:="DEU",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=357114,
                        highestPoint:=New CountryPoint("Zugspitze", 2.962),
                        lowestPoint:=New CountryPoint("Neuendorf-Sachsenbande", -0.004),
                        currency:=currencies("EUR"),
                        emoji:="🇩🇪",
                        flagImagePath:="de.png",
                        isIndependent:=True,
                        callingCode:=49,
                        topleveldomain:=".de"))

        ' Ghana
        Add(New Country(name:="Ghana",
                        officialName:="Republic of Ghana",
                        capitalCity:="Accra",
                        countryCode:="GHA",
                        continent:="Africa",
                        affiliations:={"United Nations", "Commonwealth of Nations", "African Union"},
                        areaInKM:=238533,
                        highestPoint:=New CountryPoint("Mount Afadjato", 0.88),
                        lowestPoint:=New CountryPoint("Gulf of Guinea", 0),
                        currency:=currencies("GHS"),
                        emoji:="🇬🇭",
                        flagImagePath:="gh.png",
                        isIndependent:=True,
                        callingCode:=233,
                        topleveldomain:=".gh"))

        ' Gibraltar
        Add(New Country(name:="Gibraltar",
                        officialName:="Gibraltar",
                        capitalCity:="Gibraltar",
                        countryCode:="GIB",
                        continent:="Europe",
                        affiliations:=Nothing,
                        areaInKM:=33701,
                        highestPoint:=New CountryPoint("Rock of Gibraltar", 0.426),
                        lowestPoint:=New CountryPoint("Strait of Gibraltar", 0),
                        currency:=currencies("GIP"),
                        emoji:="🇬🇮",
                        flagImagePath:="gi.png",
                        isIndependent:=True,
                        callingCode:=350,
                        topleveldomain:=".gi"))

        ' Greece
        Add(New Country(name:="Greece",
                        officialName:="Hellenic Republic",
                        capitalCity:="Athens",
                        countryCode:="GRC",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=131957,
                        highestPoint:=New CountryPoint("Mount Olympus", 2.919),
                        lowestPoint:=New CountryPoint("Mediterranean Sea", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇬🇷",
                        flagImagePath:="gr.png",
                        isIndependent:=True,
                        callingCode:=30,
                        topleveldomain:=".gr"))

        ' Greenland
        Add(New Country(name:="Greenland",
                        officialName:="Greenland",
                        capitalCity:="Nuuk",
                        countryCode:="GRL",
                        continent:="North America",
                        affiliations:={"Nordic Council"},
                        areaInKM:=2166090,
                        highestPoint:=New CountryPoint("Gunnbjørn Fjeld", 3.7),
                        lowestPoint:=New CountryPoint("Arctic Ocean, Atlantic Ocean", 0),
                        currency:=currencies("DKK"),
                        emoji:="🇬🇱",
                        flagImagePath:="gl.png",
                        isIndependent:=False,
                        callingCode:=299,
                        topleveldomain:=".gl"))

        ' Grenada
        Add(New Country(name:="Grenada",
                        officialName:="Grenada",
                        capitalCity:="St. George's",
                        countryCode:="GRD",
                        continent:="North America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=344,
                        highestPoint:=New CountryPoint("Mount Saint Catherine", 0.84),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("XCD"),
                        emoji:="🇬🇩",
                        flagImagePath:="gd.png",
                        isIndependent:=True,
                        callingCode:=1473,
                        topleveldomain:=".gd"))

        ' Guadeloupe
        Add(New Country(name:="Guadeloupe",
                        officialName:="Guadeloupe",
                        capitalCity:="Basse-Terre",
                        countryCode:="GLP",
                        continent:="North America",
                        affiliations:=Nothing,
                        areaInKM:=1.628,
                        highestPoint:=New CountryPoint("La Grande Soufrière on Basse-Terre Island", 1.484),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("EUR"),
                        emoji:="🇬🇩",
                        flagImagePath:="gp.png",
                        isIndependent:=False,
                        callingCode:=590,
                        topleveldomain:=".gp"))

        ' Guam
        Add(New Country(name:="Guam",
                        officialName:="Guam",
                        capitalCity:="Hagåtña",
                        countryCode:="GUM",
                        continent:="Oceania",
                        affiliations:={"Pacific Community"},
                        areaInKM:=529,
                        highestPoint:=New CountryPoint("Mount Lamlam", 0.406),
                        lowestPoint:=New CountryPoint("Pacific Ocean", 0),
                        currency:=currencies("USD"),
                        emoji:="🇬🇺",
                        flagImagePath:="gu.png",
                        isIndependent:=False,
                        callingCode:=1671,
                        topleveldomain:=".gu"))

        ' Guatemala
        Add(New Country(name:="Guatemala",
                        officialName:="Republic of Guatemala",
                        capitalCity:="Guatemala City",
                        countryCode:="GTM",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Central American Integration System"},
                        areaInKM:=108889,
                        highestPoint:=New CountryPoint("Volcán Tajumulco", 4.22),
                        lowestPoint:=New CountryPoint("Pacific Ocean, Caribbean Sea", 0),
                        currency:=currencies("GTQ"),
                        emoji:="🇬🇹",
                        flagImagePath:="gt.png",
                        isIndependent:=True,
                        callingCode:=502,
                        topleveldomain:=".gt"))

        ' Guernsey
        Add(New Country(name:="Guernsey",
                        officialName:="Bailiwick of Guernsey",
                        capitalCity:="St. Peter Port",
                        countryCode:="GGY",
                        continent:="Europe",
                        affiliations:=Nothing,
                        areaInKM:=78,
                        highestPoint:=New CountryPoint("Le Moulin", 0.114),
                        lowestPoint:=New CountryPoint("English Channel", 0),
                        currency:=currencies("GGP"),
                        emoji:="🇬🇬",
                        flagImagePath:="gg.png",
                        isIndependent:=False,
                        callingCode:=44,
                        topleveldomain:=".gg"))

        ' Guinea
        Add(New Country(name:="Guinea",
                        officialName:="Republic of Guinea",
                        capitalCity:="Conakry",
                        countryCode:="GIN",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=245857,
                        highestPoint:=New CountryPoint("Mont Nimba", 1.752),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("GNF"),
                        emoji:="🇬🇳",
                        flagImagePath:="gn.png",
                        isIndependent:=True,
                        callingCode:=224,
                        topleveldomain:=".gn"))


        ' Guinea-Bissau
        Add(New Country(name:="Guinea-Bissau",
                        officialName:="Republic of Guinea-Bissau",
                        capitalCity:="Bissau",
                        countryCode:="GNB",
                        continent:="Africa",
                        affiliations:={"United Nations", "African Union", "Organisation of Islamic Cooperation"},
                        areaInKM:=36125,
                        highestPoint:=New CountryPoint("Bissau", 0.3),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("XOF"),
                        emoji:="🇬🇼",
                        flagImagePath:="gw.png",
                        isIndependent:=True,
                        callingCode:=245,
                        topleveldomain:=".gw"))

        ' Guyana
        Add(New Country(name:="Guyana",
                        officialName:="Co-operative Republic of Guyana",
                        capitalCity:="Georgetown",
                        countryCode:="GUY",
                        continent:="South America",
                        affiliations:={"United Nations", "Commonwealth of Nations", "Organization of American States", "Union of South American Nations", "Caribbean Community", "Organisation of Islamic Cooperation"},
                        areaInKM:=214969,
                        highestPoint:=New CountryPoint("Mount Roraima", 2.772),
                        lowestPoint:=New CountryPoint("Atlantic Ocean", 0),
                        currency:=currencies("GYD"),
                        emoji:="🇬🇾",
                        flagImagePath:="gy.png",
                        isIndependent:=True,
                        callingCode:=592,
                        topleveldomain:=".gy"))

        ' Haiti
        Add(New Country(name:="Haiti",
                        officialName:="Republic of Haiti",
                        capitalCity:="Port-au-Prince",
                        countryCode:="HTI",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Caribbean Community"},
                        areaInKM:=27750,
                        highestPoint:=New CountryPoint("Pic la Selle", 2.68),
                        lowestPoint:=New CountryPoint("Caribbean Sea", 0),
                        currency:=currencies("HTG"),
                        emoji:="🇭🇹",
                        flagImagePath:="ht.png",
                        isIndependent:=True,
                        callingCode:=509,
                        topleveldomain:=".ht"))

        ' Haiti
        Add(New Country(name:="Heard Island and McDonald Islands",
                        officialName:="Heard Island and McDonald Islands",
                        capitalCity:=Nothing,
                        countryCode:="HMD",
                        continent:=Nothing,
                        affiliations:=Nothing,
                        areaInKM:=412,
                        highestPoint:=New CountryPoint("Big Ben", 2.745),
                        lowestPoint:=New CountryPoint("Indian Ocean", 0),
                        currency:=currencies("HMD"),
                        emoji:="🇭🇲",
                        flagImagePath:="hm.png",
                        isIndependent:=False,
                        callingCode:=0,
                        topleveldomain:=".hm"))

        ' Honduras
        Add(New Country(name:="Honduras",
                        officialName:="Republic of Honduras",
                        capitalCity:="Tegucigalpa",
                        countryCode:="HND",
                        continent:="North America",
                        affiliations:={"United Nations", "Organization of American States", "Central American Integration System"},
                        areaInKM:=112492,
                        highestPoint:=New CountryPoint("Cerro Las Minas", 2.745),
                        lowestPoint:=New CountryPoint("Caribbean Sea, Pacific Ocean", 0),
                        currency:=currencies("HNL"),
                        emoji:="🇭🇳",
                        flagImagePath:="hn.png",
                        isIndependent:=True,
                        callingCode:=504,
                        topleveldomain:=".hn"))

        ' Hong Kong
        Add(New Country(name:="Hong Kong",
                        officialName:="Hong Kong Special Administrative Region of the People's Republic of China",
                        capitalCity:="City of Victoria",
                        countryCode:="HKG",
                        continent:="Asia",
                        affiliations:=Nothing,
                        areaInKM:=1104,
                        highestPoint:=New CountryPoint("Tai Mo Shan", 0.958),
                        lowestPoint:=New CountryPoint("China Sea", 0),
                        currency:=currencies("HKD"),
                        emoji:="🇭🇰",
                        flagImagePath:="hk.png",
                        isIndependent:=False,
                        callingCode:=852,
                        topleveldomain:=".hk"))

        ' Hungary
        Add(New Country(name:="Hungary",
                        officialName:="Hungary",
                        capitalCity:="Budapest",
                        countryCode:="HUN",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=93028,
                        highestPoint:=New CountryPoint("Kékes", 1.014),
                        lowestPoint:=New CountryPoint("Tisza ", 0.076),
                        currency:=currencies("HUF"),
                        emoji:="🇭🇺",
                        flagImagePath:="hu.png",
                        isIndependent:=False,
                        callingCode:=36,
                        topleveldomain:=".hu"))


        ' Iceland
        Add(New Country(name:="Iceland",
                        officialName:="Iceland",
                        capitalCity:="Reykjavik",
                        countryCode:="ISL",
                        continent:="Europe",
                        affiliations:={"United Nations", "NATO", "Nordic Council"},
                        areaInKM:=103000,
                        highestPoint:=New CountryPoint("Hvannadalshnúkur", 2.11),
                        lowestPoint:=New CountryPoint("Atlantic Ocean ", 0),
                        currency:=currencies("ISK"),
                        emoji:="🇮🇸",
                        flagImagePath:="is.png",
                        isIndependent:=True,
                        callingCode:=354,
                        topleveldomain:=".is"))


        ' India
        Add(New Country(name:="India",
                        officialName:="Republic of India",
                        capitalCity:="New Delhi",
                        countryCode:="IND",
                        continent:="Asia",
                        affiliations:={"United Nations", "Commonwealth of Nations"},
                        areaInKM:=3287260,
                        highestPoint:=New CountryPoint("Kangchenjunga", 8.586),
                        lowestPoint:=New CountryPoint("Kuttanad ", -0.002),
                        currency:=currencies("INR"),
                        emoji:="🇮🇳",
                        flagImagePath:="in.png",
                        isIndependent:=True,
                        callingCode:=91,
                        topleveldomain:=".in"))

        ' Indonesia | Contenents: Asia, Oceania
        Add(New Country(name:="Indonesia",
                        officialName:="Republic of Indonesia",
                        capitalCity:="Jakarta",
                        countryCode:="IDN",
                        continent:="Asia",
                        affiliations:={"United Nations", "Association of Southeast Asian Nations", "Organisation of Islamic Cooperation"},
                        areaInKM:=1910930,
                        highestPoint:=New CountryPoint("Puncak Jaya", 4.884),
                        lowestPoint:=New CountryPoint("Indian Ocean, Pacific Ocean", 0),
                        currency:=currencies("IDR"),
                        emoji:="🇮🇩",
                        flagImagePath:="id.png",
                        isIndependent:=True,
                        callingCode:=62,
                        topleveldomain:=".id"))

        ' Iran | TLD: .ir, ایران.
        Add(New Country(name:="Iran",
                        officialName:="Islamic Republic of Iran",
                        capitalCity:="Tehran",
                        countryCode:="IRN",
                        continent:="Asia",
                        affiliations:={"United Nations", "Organisation of Islamic Cooperation", "OPEC"},
                        areaInKM:=1648200,
                        highestPoint:=New CountryPoint("Puncak Jaya", 5.61),
                        lowestPoint:=New CountryPoint("Caspian Sea", -0.028),
                        currency:=currencies("IRR"),
                        emoji:="🇮🇷",
                        flagImagePath:="ir.png",
                        isIndependent:=True,
                        callingCode:=98,
                        topleveldomain:=".ir"))

        ' Iran | TLD: .ir, ایران.
        Add(New Country(name:="Iran",
                        officialName:="Islamic Republic of Iran",
                        capitalCity:="Tehran",
                        countryCode:="IRN",
                        continent:="Asia",
                        affiliations:={"United Nations", "Organisation of Islamic Cooperation", "OPEC"},
                        areaInKM:=1648200,
                        highestPoint:=New CountryPoint("Puncak Jaya", 5.61),
                        lowestPoint:=New CountryPoint("Caspian Sea", -0.028),
                        currency:=currencies("IRR"),
                        emoji:="🇮🇷",
                        flagImagePath:="ir.png",
                        isIndependent:=True,
                        callingCode:=98,
                        topleveldomain:=".ir"))

        ' Iraq
        Add(New Country(name:="Iran",
                        officialName:="Republic of Iraq",
                        capitalCity:="Baghdad",
                        countryCode:="IRQ",
                        continent:="Asia",
                        affiliations:={"United Nations", "Arab League", "Organisation of Islamic Cooperation", "OPEC"},
                        areaInKM:=438317,
                        highestPoint:=New CountryPoint("Cheekha Dar", 3.611),
                        lowestPoint:=New CountryPoint("Persian Gulf", 0),
                        currency:=currencies("IQD"),
                        emoji:="🇮🇶",
                        flagImagePath:="iq.png",
                        isIndependent:=True,
                        callingCode:=964,
                        topleveldomain:=".iq"))

        ' Ireland
        Add(New Country(name:="Ireland",
                        officialName:="Republic of Ireland",
                        capitalCity:="Dublin",
                        countryCode:="IRL",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union"},
                        areaInKM:=70273,
                        highestPoint:=New CountryPoint("Carrauntoohil", 1.038),
                        lowestPoint:=New CountryPoint("North Slob", -0.003),
                        currency:=currencies("EUR"),
                        emoji:="🇮🇪",
                        flagImagePath:="ie.png",
                        isIndependent:=True,
                        callingCode:=353,
                        topleveldomain:=".ie"))

        ' Isle of Man| Curencies: GBP, IMP
        Add(New Country(name:="Isle of Man",
                        officialName:="Isle of Man",
                        capitalCity:="Douglas",
                        countryCode:="IMN",
                        continent:="Europe",
                        affiliations:=Nothing,
                        areaInKM:=572,
                        highestPoint:=New CountryPoint("Snaefell", 0.621),
                        lowestPoint:=New CountryPoint("Irish Sea", 0),
                        currency:=currencies("GBP"),
                        emoji:="🇮🇲",
                        flagImagePath:="im.png",
                        isIndependent:=False,
                        callingCode:=44,
                        topleveldomain:=".im"))

        ' Israel
        Add(New Country(name:="Israel",
                        officialName:="State of Israel",
                        capitalCity:="Jerusalem",
                        countryCode:="ISR",
                        continent:="Asia",
                        affiliations:={"United Nations"},
                        areaInKM:=20770,
                        highestPoint:=New CountryPoint("Mount Meron", 1.208),
                        lowestPoint:=New CountryPoint("Dead Sea", -0.428),
                        currency:=currencies("ILS"),
                        emoji:="🇮🇱",
                        flagImagePath:="il.png",
                        isIndependent:=True,
                        callingCode:=972,
                        topleveldomain:=".il"))

        ' Italy
        Add(New Country(name:="Italy",
                        officialName:="Italian Republic",
                        capitalCity:="Rome",
                        countryCode:="ITA",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=301339,
                        highestPoint:=New CountryPoint("Monte Bianco", 4.81),
                        lowestPoint:=New CountryPoint("Jolanda di Savoia", -0.003),
                        currency:=currencies("EUR"),
                        emoji:="🇮🇹",
                        flagImagePath:="it.png",
                        isIndependent:=True,
                        callingCode:=39,
                        topleveldomain:=".it"))

        ' Italy
        Add(New Country(name:="Italy",
                        officialName:="Italian Republic",
                        capitalCity:="Rome",
                        countryCode:="ITA",
                        continent:="Europe",
                        affiliations:={"United Nations", "European Union", "NATO"},
                        areaInKM:=301339,
                        highestPoint:=New CountryPoint("Monte Bianco", 4.81),
                        lowestPoint:=New CountryPoint("Jolanda di Savoia", -0.003),
                        currency:=currencies("EUR"),
                        emoji:="🇮🇹",
                        flagImagePath:="it.png",
                        isIndependent:=True,
                        callingCode:=39,
                        topleveldomain:=".it"))


    End Sub


End Class
