''' <summary>
''' A <see cref="List(Of Currency)"/>
''' </summary>
Public Class Currencies
    Inherits List(Of Currency)

    Public Sub New()
        Add(New Currency("United Arab Emirates dirham", "AED"))
        Add(New Currency("Afghan afghani", "AFN"))
        Add(New Currency("Albanian lek", "ALL"))
        Add(New Currency("Armenian dram", "AMD"))
        Add(New Currency("Angolan kwanza", "AOA"))
        Add(New Currency("Argentine peso", "ARS"))
        Add(New Currency("Australian dollar", "AUD"))
        Add(New Currency("Azerbaijani manat", "AZN"))
        Add(New Currency("Bosnia and Herzegovina convertible mark", "BAM"))
        Add(New Currency("Barbadian dollar", "BBD"))
        Add(New Currency("Bangladeshi taka", "BDT"))
        Add(New Currency("Bulgarian lev", "BGN"))
        Add(New Currency("Bahraini dinar", "BHD"))
        Add(New Currency("Burundian franc", "BIF"))
        Add(New Currency("Brunei dollar", "BND"))
        Add(New Currency("Bolivian boliviano", "BOB"))
        Add(New Currency("Brazilian real", "BRL"))
        Add(New Currency("Bahamian dollar", "BSD"))
        Add(New Currency("Bhutanese ngultrum", "BTN"))
        Add(New Currency("Botswana pula", "BWP"))
        Add(New Currency("Belarusian ruble", "BYN"))
        Add(New Currency("Belize dollar", "BZD"))
        Add(New Currency("Canadian dollar", "CAD"))
        Add(New Currency("Congolese franc", "CFD"))
        Add(New Currency("Swiss franc", "CHF"))
        Add(New Currency("Chilean peso", "CLP"))
        Add(New Currency("Chinese yuan", "CNY"))
        Add(New Currency("Colombian peso", "COP"))
        Add(New Currency("Costa Rican colón", "CRC"))
        Add(New Currency("Cuban peso", "CUP"))
        Add(New Currency("Cape Verdean escudo", "CVE"))
        Add(New Currency("Czech koruna", "CZK"))
        Add(New Currency("Djiboutian franc", "DJF"))
        Add(New Currency("Danish krone", "DKK"))
        Add(New Currency("Dominican peso", "DOP"))
        Add(New Currency("Algerian dinar", "DZD"))
        Add(New Currency("Egyptian pound", "EGP"))
        Add(New Currency("Eritrean nakfa", "ERN"))
        Add(New Currency("Ethiopian birr", "ETB"))
        Add(New Currency("Euro", "EUR"))
        Add(New Currency("Fijian dollar", "FJD"))
        Add(New Currency("British pound", "GBP"))
        Add(New Currency("Georgian lari", "GEL"))
        Add(New Currency("Ghanaian cedi", "GHS"))
        Add(New Currency("Gambian dalasi", "GMD"))
        Add(New Currency("Guinean franc", "GNF"))
        Add(New Currency("Guatemalan quetzal", "GTQ"))
        Add(New Currency("Guyanese dollar", "GYD"))
        Add(New Currency("Honduran lempira", "HNL"))
        Add(New Currency("Croatian kuna", "HRK"))
        Add(New Currency("Haitian gourde", "HTG"))
        Add(New Currency("Hungarian forint", "HUF"))
        Add(New Currency("Indonesian rupiah", "IDR"))
        Add(New Currency("Israeli new shekel", "ILS"))
        Add(New Currency("Indian rupee", "INR"))
        Add(New Currency("Iraqi dinar", "IDQ"))
        Add(New Currency("Iranian rial", "IRR"))
        Add(New Currency("Icelandic króna", "ISK"))
        Add(New Currency("Jamaican dollar", "JMD"))
        Add(New Currency("Jordanian dinar", "JOD"))
        Add(New Currency("Japanese yen", "JPY"))
        Add(New Currency("Kenyan shilling", "KES"))
        Add(New Currency("Kyrgyzstani som", "KGS"))
        Add(New Currency("Cambodian riel", "KHR"))
        Add(New Currency("Comorian franc", "KMF"))
        Add(New Currency("North Korean won", "KPW"))
        Add(New Currency("South Korean won", "KRW"))
        Add(New Currency("Kuwaiti dinar", "KWD"))
        Add(New Currency("Kazakhstani tenge", "KZT"))
        Add(New Currency("Lao kip", "LAK"))
        Add(New Currency("Lebanese pound", "LBP"))
        Add(New Currency("Sri Lankan rupee", "LKR"))
        Add(New Currency("Liberian dollar", "LRD"))
        Add(New Currency("Lesotho loti", "LSL"))
        Add(New Currency("Libyan dinar", "LYD"))
        Add(New Currency("Moroccan dirham", "MAD"))
        Add(New Currency("Moldovan leu", "MDL"))
        Add(New Currency("Malagasy ariary", "MGA"))
        Add(New Currency("Macedonian denar", "MKD"))
        Add(New Currency("Burmese kyat", "MMK"))
        Add(New Currency("Mongolian tögrög", "MNT"))
        Add(New Currency("Mauritanian ouguiya", "MRO"))
        Add(New Currency("Mauritian rupee", "MUR"))
        Add(New Currency("Maldivian rufiyaa", "MVR"))
        Add(New Currency("Malawian kwacha", "MWK"))
        Add(New Currency("Mexican peso", "MXN"))
        Add(New Currency("Malaysian ringgit", "MYR"))
        Add(New Currency("Mozambican metical", "MZN"))
        Add(New Currency("Namibian dollar", "NAD"))
        Add(New Currency("Nigerian naira", "NGN"))
        Add(New Currency("Nicaraguan córdoba", "NIO"))
        Add(New Currency("Norwegian krone", "NOK"))
        Add(New Currency("Nepalese rupee", "NPR"))
        Add(New Currency("New Zealand dollar", "NZD"))
        Add(New Currency("Omani rial", "OMR"))
        Add(New Currency("Panamanian balboa", "PAB"))
        Add(New Currency("Peruvian sol", "PEN"))
        Add(New Currency("Papua New Guinean kina", "PGK"))
        Add(New Currency("Philippine peso", "PHP"))
        Add(New Currency("Pakistani rupee", "PKR"))
        Add(New Currency("Polish zloty", "PLN"))
        Add(New Currency("Paraguayan guaraní", "PYC"))
        Add(New Currency("Qatari riyal", "QAR"))
        Add(New Currency("Romanian leu", "RON"))
        Add(New Currency("Serbian dinar", "RSD"))
        Add(New Currency("Russian ruble", "RUB"))
        Add(New Currency("Rwandan franc", "RWF"))
        Add(New Currency("Saudi riyal", "SAR"))
        Add(New Currency("Solomon Islands dollar", "SBD"))
        Add(New Currency("Seychellois rupee", "SCR"))
        Add(New Currency("Sudanese pound", "SDG"))
        Add(New Currency("Swedish krona", "SEK"))
        Add(New Currency("Singapore dollar", "SGD"))
        Add(New Currency("Sierra Leonean leone", "SLL"))
        Add(New Currency("Somali shilling", "SOS"))
        Add(New Currency("Surinamese dollar", "SRD"))
        Add(New Currency("South Sudanese pound", "SSP"))
        Add(New Currency("São Tomé and Príncipe dobra", "STD"))
        Add(New Currency("Syrian pound", "SYP"))
        Add(New Currency("Swazi lilangeni", "SZL"))
        Add(New Currency("Thai baht", "THB"))
        Add(New Currency("Tajikistani somoni", "TJS"))
        Add(New Currency("Turkmenistan manat", "TMT"))
        Add(New Currency("Tunisian dinar", "TND"))
        Add(New Currency("Tongan pa'anga", "TOP"))
        Add(New Currency("Turkish lira", "TRY"))
        Add(New Currency("Trinidad and Tobago dollar", "TTD"))
        Add(New Currency("New Taiwan dollar", "TWD"))
        Add(New Currency("Tanzanian shilling", "TZS"))
        Add(New Currency("Ukrainian hryvnia", "UAH"))
        Add(New Currency("Ugandan shilling", "UGX"))
        Add(New Currency("United States dollar", "USD"))
        Add(New Currency("Uruguayan peso", "UYU"))
        Add(New Currency("Uzbekistani som", "UZS"))
        Add(New Currency("Venezuelan bolívar", "VEF"))
        Add(New Currency("Vietnamese dong", "VND"))
        Add(New Currency("Vanuatu vatu", "VUV"))
        Add(New Currency("Samoan tala", "WST"))
        Add(New Currency("Central African CFA franc", "XAF"))
        Add(New Currency("East Caribbean dollar", "XCD"))
        Add(New Currency("West African CFA franc", "XOF"))
        Add(New Currency("Yemeni rial", "YER"))
        Add(New Currency("South African rand", "ZAR"))
        Add(New Currency("Zambian kwacha", "ZMW"))
    End Sub

    Default Public Shadows ReadOnly Property [Item](IsoCode As String) As Currency
        Get
            Return Me.SingleOrDefault(Function(i) i.IsoCode = IsoCode)
        End Get
    End Property

End Class
